'use client'

import BottomBar from '@/components/organism/BottomBar'
import Header from '@/components/organism/Header'
import useWindowSize from '@/utils/hooks/useWindowSize'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { width } = useWindowSize()

  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        {width < 768 && <BottomBar />}
      </body>
    </html>
  )
}
